# Need to be consistent with cert-manager-webhook-huawei
groupName: acme.mycompany.com

email: "hwclouds.cs@huawei.com"

appKey: "123456"
appSecret: "123456"
# https://developer.huaweicloud.com/endpoint?DNS
region: cn-north-4
# https://console.huaweicloud.com/apiexplorer/#/openapi/DNS/debug?api=ListPublicZones
zoneId: "123456"

dnsNames:
  - 'xxx.cn'
  - '*.xxx.cn'

# Please install reflector
# Refer to https://github.com/EmberStack/kubernetes-reflector
# This is use to sync secret to other namespace
annotations: {}
  # reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  # reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
  # reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  # reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""