apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}
  dnsNames:
    {{- range .Values.dnsNames }}
    - {{ . | quote }}
    {{- end }}
  renewBefore: 360h
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Release.Name }}
{{- if .Values.annotations }}
  secretTemplate:
    annotations:
{{ toYaml .Values.annotations | indent 6 }}
{{- end }}
