name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'Docker tag'
        required: true
        default: 'latest'
      PLATFORMS:
        description: '构建的平台，多平台用逗号分隔'
        required: false
        default: 'linux/amd64'

jobs:
  build:
    environment: Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: 登录 DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 构建并推送 Docker 镜像
        run: |
          IMAGE_NAME=genchsusu/cert-manager-webhook-huawei
          docker buildx build --platform ${{ github.event.inputs.PLATFORMS }} \
            --tag "$IMAGE_NAME:${{ github.event.inputs.IMAGE_TAG }}" \
            --push .
